package Visual;

import Controle.Controler_Cliente;
import Controle.Controler_Servico;
import Controle.Controler_Taxi;
import Objetos.Cliente;
import Objetos.Servico;
import Objetos.Taxi;
import java.util.ArrayList;
import java.util.Vector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Guilherme
 */
public class VisualizarServicos extends javax.swing.JFrame {

    Controler_Servico serv = new Controler_Servico();
    ArrayList< Servico> arraydeservico = new ArrayList< Servico>();
    public VisualizarServicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldPlaca = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListServico = new javax.swing.JList();
        jComboBoxStatus = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome do responsavel");

        jLabel2.setText("Placa");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome do cliente");

        jLabel4.setText("Status");

        jListServico.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Controler_Cliente client = new Controler_Cliente();
        Controler_Taxi taxis = new Controler_Taxi();

        String BuscarS;

        arraydeservico = serv.Visualizar_servico(",,,,,");

        Vector t = new Vector();
        String temp;
        ArrayList< Cliente> arraydecliente = new ArrayList< Cliente>();
        ArrayList< Taxi> arraydetaxi = new ArrayList< Taxi>();

        arraydecliente = client.Visualizar_Cliente(",,");
        Vector VClientes = new Vector();

        for (int cont = 0; cont < arraydecliente.size(); cont++) {
            temp = "" + arraydecliente.get(cont).getCod() + ", " + arraydecliente.get(cont).getNome() + ", CPF: " + arraydecliente.get(cont).getCpf() + ", Telefone: " + arraydecliente.get(cont).getTelefone();
            VClientes.add(temp);
        }

        arraydetaxi = taxis.Visualizar_taxi(",,,,");
        Vector VTaxis = new Vector();

        for (int cont = 0; cont < arraydetaxi.size(); cont++) {
            temp = "" + arraydetaxi.get(cont).getCod() + ", Taxista: " + arraydetaxi.get(cont).getResp_taxi() + ", Placa: " + arraydetaxi.get(cont).getPlaca() + ", Telefone: " + arraydetaxi.get(cont).getTelefone();
            VTaxis.add(temp);
        }

        for (int cont = 0; cont < arraydeservico.size(); cont++) {

            temp = "" + arraydeservico.get(cont).getCod() + ", Cliente: " + RetornaRestoString(VClientes, "" + arraydeservico.get(cont).getCodcliente()) + ", " + RetornaRestoString(VTaxis, "" + arraydeservico.get(cont).getCodtaxi()) + ", Inicio: " + arraydeservico.get(cont).getEdereco_inicio() + ", Fim: " + arraydeservico.get(cont).getEdereco_fim() + ", " + arraydeservico.get(cont).getStatus();
            t.add(temp);
        }
        jListServico.setListData(t);

        jListServico.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListServicoValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListServico);

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Aberto", "Finalizado", "Cancelado" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(jTextFieldNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)
                        .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButtonBuscar)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private String RetornaRestoString(Vector VClientes, String s) {
        String deletar = "";
        String resto = "";
        for (int i = 0; i < VClientes.size(); i++) {
            String a = (String) VClientes.get(i);
            deletar = "";
            for (int cont = 0; a.charAt(cont) != ','; cont++) {
                deletar += a.charAt(cont);
                if ((Long.parseLong(s) == Long.parseLong(deletar)) && (a.charAt(cont + 1) == ',')) {
                    for (cont += 3; cont < a.length(); cont++) {
                        resto += a.charAt(cont);
                    }
                    return resto;
                }
            }

        }
        return "Inconcistencia no banco.";
    }
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        Controler_Cliente client = new Controler_Cliente();
        Controler_Taxi taxis = new Controler_Taxi();

        String BuscarS;
        BuscarS = jTextFieldNome.getText() + ",";
        BuscarS += jTextFieldPlaca.getText() + ",";
        BuscarS += jTextFieldCliente.getText() + ",";
        if (jComboBoxStatus.getSelectedItem() != " ") {
            BuscarS += jComboBoxStatus.getSelectedItem() + ",";
        } else {
            BuscarS += ",";
        }

        arraydeservico = serv.Visualizar_servico(BuscarS);

        Vector t = new Vector();
        String temp;
        ArrayList< Cliente> arraydecliente = new ArrayList< Cliente>();
        ArrayList< Taxi> arraydetaxi = new ArrayList< Taxi>();

        arraydecliente = client.Visualizar_Cliente(",,");
        Vector VClientes = new Vector();

        for (int cont = 0; cont < arraydecliente.size(); cont++) {
            temp = "" + arraydecliente.get(cont).getCod() + ", " + arraydecliente.get(cont).getNome() + ", CPF: " + arraydecliente.get(cont).getCpf() + ", Telefone: " + arraydecliente.get(cont).getTelefone();
            VClientes.add(temp);
        }

        arraydetaxi = taxis.Visualizar_taxi(",,,,");
        Vector VTaxis = new Vector();

        for (int cont = 0; cont < arraydetaxi.size(); cont++) {
            temp = "" + arraydetaxi.get(cont).getCod() + ", Taxista: " + arraydetaxi.get(cont).getResp_taxi() + ", Placa: " + arraydetaxi.get(cont).getPlaca() + ", Telefone: " + arraydetaxi.get(cont).getTelefone();
            VTaxis.add(temp);
        }

        for (int cont = 0; cont < arraydeservico.size(); cont++) {

            temp = "" + arraydeservico.get(cont).getCod() + ", Cliente: " + RetornaRestoString(VClientes, "" + arraydeservico.get(cont).getCodcliente()) + ", " + RetornaRestoString(VTaxis, "" + arraydeservico.get(cont).getCodtaxi()) + ", Inicio: " + arraydeservico.get(cont).getEdereco_inicio() + ", Fim: " + arraydeservico.get(cont).getEdereco_fim() + ", " + arraydeservico.get(cont).getStatus();
            t.add(temp);
        }
        jListServico.setListData(t);
        jButtonExcluir.setEnabled(false);

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        EditarServico user = new EditarServico(arraydeservico.get(jListServico.getSelectedIndex()));
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        String a = (String) jListServico.getSelectedValue();
        String deletar = "";
        for (int cont = 0; a.charAt(cont) != ','; cont++) {
            deletar += a.charAt(cont);
        }
        serv.Excluir_Servico(Long.parseLong(deletar));

        Controler_Cliente client = new Controler_Cliente();
        Controler_Taxi taxis = new Controler_Taxi();
        
        String BuscarS;
        BuscarS = jTextFieldNome.getText() + ",";
        BuscarS += jTextFieldPlaca.getText() + ",";
        BuscarS += jTextFieldCliente.getText() + ",";
        if (jComboBoxStatus.getSelectedItem() != " ") {
            BuscarS += jComboBoxStatus.getSelectedItem() + ",";
        } else {
            BuscarS += ",";
        }

        arraydeservico = serv.Visualizar_servico(BuscarS);

        Vector t = new Vector();
        String temp;
        ArrayList< Cliente> arraydecliente = new ArrayList< Cliente>();
        ArrayList< Taxi> arraydetaxi = new ArrayList< Taxi>();

        arraydecliente = client.Visualizar_Cliente(",,");
        Vector VClientes = new Vector();

        for (int cont = 0; cont < arraydecliente.size(); cont++) {
            temp = "" + arraydecliente.get(cont).getCod() + ", " + arraydecliente.get(cont).getNome() + ", CPF: " + arraydecliente.get(cont).getCpf() + ", Telefone: " + arraydecliente.get(cont).getTelefone();
            VClientes.add(temp);
        }

        arraydetaxi = taxis.Visualizar_taxi(",,,,");
        Vector VTaxis = new Vector();

        for (int cont = 0; cont < arraydetaxi.size(); cont++) {
            temp = "" + arraydetaxi.get(cont).getCod() + ", Taxista: " + arraydetaxi.get(cont).getResp_taxi() + ", Placa: " + arraydetaxi.get(cont).getPlaca() + ", Telefone: " + arraydetaxi.get(cont).getTelefone();
            VTaxis.add(temp);
        }

        for (int cont = 0; cont < arraydeservico.size(); cont++) {

            temp = "" + arraydeservico.get(cont).getCod() + ", Cliente: " + RetornaRestoString(VClientes, "" + arraydeservico.get(cont).getCodcliente()) + ", " + RetornaRestoString(VTaxis, "" + arraydeservico.get(cont).getCodtaxi()) + ", Inicio: " + arraydeservico.get(cont).getEdereco_inicio() + ", Fim: " + arraydeservico.get(cont).getEdereco_fim() + ", " + arraydeservico.get(cont).getStatus();
            t.add(temp);
        }
        jListServico.setListData(t);
        jButtonExcluir.setEnabled(false);

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jListServicoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListServicoValueChanged
        if (jListServico.getSelectedIndex() >= 0) {
            jButtonExcluir.setEnabled(true);
            jButtonEditar.setEnabled(true);
        } else {
            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);
        }

    }//GEN-LAST:event_jListServicoValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JComboBox jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jListServico;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
