package Visual;


import Controle.Controler_Cliente;
import Objetos.Cliente;
import Visual.EditarCliente;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Guilherme
 */
public class VisualizarCliente extends javax.swing.JFrame {

    Controler_Cliente client = new Controler_Cliente();

    public VisualizarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Fechar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        ArrayList< Cliente> arraydecliente = new ArrayList< Cliente>();

        arraydecliente = client.Visualizar_Cliente(",,,");
        Vector t = new Vector();
        String temp;

        for (int cont = 0; cont < arraydecliente.size(); cont++) {
            temp = "" + arraydecliente.get(cont).getCod() + ", " + arraydecliente.get(cont).getNome() + ", " + arraydecliente.get(cont).getCpf() + ", " + arraydecliente.get(cont).getTelefone() + ", " + arraydecliente.get(cont).getData_nascimento() + ", " + arraydecliente.get(cont).getEmail();
            t.add(temp);
        }
        jList1.setListData(t);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList< Cliente> arraydecliente = new ArrayList< Cliente>();
        String BuscarS;
        BuscarS = jTextField1.getText() + ",";
        BuscarS += jTextField2.getText() + ",";
        arraydecliente = client.Visualizar_Cliente(BuscarS);
        Vector t = new Vector();
        String temp;

        for (int cont = 0; cont < arraydecliente.size(); cont++) {
            temp = "" + arraydecliente.get(cont).getCod() + ", " + arraydecliente.get(cont).getNome() + ", " + arraydecliente.get(cont).getCpf() + ", " + arraydecliente.get(cont).getTelefone() + ", " + arraydecliente.get(cont).getData_nascimento() + ", " + arraydecliente.get(cont).getEmail();
            t.add(temp);
        }
        jList1.setListData(t);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {                                         
            String BuscarS;
            EditarCliente user;
            BuscarS = (String) jList1.getSelectedValue() + ",";
            
            String BusZ = "";
            int cont;
            Vector z = new Vector();
            
            for (cont = 0; BuscarS.charAt(cont) != ',' && cont < BuscarS.length(); cont++) {
                BusZ += BuscarS.charAt(cont);
            }
            z.add(BusZ);
            for (int i = 0; i < 5; i++) {
                BusZ = "";
                for (cont++; BuscarS.charAt(cont) != ',' && cont < BuscarS.length(); cont++) {
                    if (BuscarS.charAt(cont) != ' ') {
                        BusZ += BuscarS.charAt(cont);
                    }
                }
                z.add(BusZ);
            }
            
            z.add(BusZ);
            BusZ = "";
            Vector y = new Vector();
            cont = 0;
            BuscarS = (String) z.get(4) + "-";
            for (int k = 0; k < 3; k++) {
                for (; BuscarS.charAt(cont) != '-' && cont < BuscarS.length(); cont++) {
                    BusZ += BuscarS.charAt(cont);
                }
                y.add(BusZ);
                BusZ = "";
                cont++;
            }
            SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
            String dataNasci = ((String) y.get(2) + "/" + (String) y.get(1) + "/" + (String) y.get(0));
            java.util.Date dataN = null;
            try {
                dataN = data.parse(dataNasci);
            } catch (ParseException ex) {
            }
            java.sql.Date datas = null;
            datas = new java.sql.Date(dataN.getTime());
            
            Cliente Cliente_p_editar = new Cliente(Long.parseLong((String) z.get(0)), (String) z.get(1), Long.parseLong((String) z.get(2)), Long.parseLong((String) z.get(3)), datas, (String) z.get(5));
            
            user = new EditarCliente(Cliente_p_editar);
            
            
            
            user.setVisible(true);
            this.dispose();
        } catch (ParseException ex) {
            Logger.getLogger(VisualizarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String a = (String) jList1.getSelectedValue();
        String deletar = "";
        for (int cont = 0; a.charAt(cont) != ','; cont++) {
            deletar += a.charAt(cont);
        }
        client.Excluir_Cliente(Long.parseLong(deletar));

        ArrayList< Cliente> arraydecliente = new ArrayList< Cliente>();

        arraydecliente = client.Visualizar_Cliente(",,");
        Vector t = new Vector();
        String temp;

        for (int cont = 0; cont < arraydecliente.size(); cont++) {
            temp = "" + arraydecliente.get(cont).getCod() + ", " + arraydecliente.get(cont).getNome() + ", " + arraydecliente.get(cont).getCpf() + ", " + arraydecliente.get(cont).getTelefone() + ", " + arraydecliente.get(cont).getData_nascimento() + ", " + arraydecliente.get(cont).getEmail();
            t.add(temp);
        }
        jList1.setListData(t);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (jList1.getSelectedIndex() >= 0) {
            jButton3.setEnabled(true);
            jButton2.setEnabled(true);
        } else {
            jButton3.setEnabled(false);
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jList1ValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
